Remove sonarqube-relaated stuff from jenkinsfile

diff --git a/api/Jenkinsfile b/api/Jenkinsfile
--- a/api/Jenkinsfile
+++ b/api/Jenkinsfile
@@ -1,75 +1,75 @@
-import groovy.json.JsonOutput
-import groovy.json.JsonSlurper
-import java.util.regex.Pattern
+// import groovy.json.JsonOutput
+// import groovy.json.JsonSlurper
+// import java.util.regex.Pattern
 
 /*
  * takes in a sonarqube status json payload
  * and returns the status string
  */
-def sonarGetStatus (jsonPayload) {
-  def jsonSlurper = new JsonSlurper()
-  return jsonSlurper.parseText(jsonPayload).projectStatus.status
-}
+// def sonarGetStatus (jsonPayload) {
+//   def jsonSlurper = new JsonSlurper()
+//   return jsonSlurper.parseText(jsonPayload).projectStatus.status
+// }
 
-def nodejsSonarqube() {
-    _openshift(env.STAGE_NAME, TOOLSPROJECT) {
-        String sonarLabel = "sonarqube-runner-${UUID.randomUUID().toString()}";
-        podTemplate(
-            label: sonarLabel,
-            name: sonarLabel,
-            serviceAccount: 'jenkins',
-            cloud: 'openshift',
-            slaveConnectTimeout: 300,
-            containers: [
-              containerTemplate(
-                name: 'jnlp',
-                image: 'registry.access.redhat.com/openshift3/jenkins-agent-nodejs-8-rhel7:v3.11.161',
-                resourceRequestCpu: '500m',
-                resourceLimitCpu: '1000m',
-                resourceRequestMemory: '2Gi',
-                resourceLimitMemory: '2Gi',
-                workingDir: '/tmp',
-                command: '',
-                args: '${computer.jnlpmac} ${computer.name}',
-              )
-            ]
-        ) {
-            node(sonarLabel) {
-                checkout scm
-                dir('.jenkins/sonarqube/sonar-runner') {
-                    try {
-                        def SONARQUBE_URL = ${SONARQUBE_URL}
-                        def SONARQUBE_STATUS_URL = "${SONARQUBE_URL}/api/qualitygates/project_status?projectKey='invasives-app'"
+// def nodejsSonarqube() {
+//     _openshift(env.STAGE_NAME, TOOLSPROJECT) {
+//         String sonarLabel = "sonarqube-runner-${UUID.randomUUID().toString()}";
+//         podTemplate(
+//             label: sonarLabel,
+//             name: sonarLabel,
+//             serviceAccount: 'jenkins',
+//             cloud: 'openshift',
+//             slaveConnectTimeout: 300,
+//             containers: [
+//               containerTemplate(
+//                 name: 'jnlp',
+//                 image: 'registry.access.redhat.com/openshift3/jenkins-agent-nodejs-8-rhel7:v3.11.161',
+//                 resourceRequestCpu: '500m',
+//                 resourceLimitCpu: '1000m',
+//                 resourceRequestMemory: '2Gi',
+//                 resourceLimitMemory: '2Gi',
+//                 workingDir: '/tmp',
+//                 command: '',
+//                 args: '${computer.jnlpmac} ${computer.name}',
+//               )
+//             ]
+//         ) {
+//             node(sonarLabel) {
+//                 checkout scm
+//                 dir('.jenkins/sonarqube/sonar-runner') {
+//                     try {
+//                         def SONARQUBE_URL = ${SONARQUBE_URL}
+//                         def SONARQUBE_STATUS_URL = "${SONARQUBE_URL}/api/qualitygates/project_status?projectKey='invasives-app'"
 
-                        // run scan
-                        sh "npm install typescript"
-                        sh returnStdout: true, script: "./gradlew sonarqube -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.projectKey='invasives-app' -Dsonar.verbose=true --stacktrace --info"
-                        sleep(30)
+//                         // run scan
+//                         sh "npm install typescript"
+//                         sh returnStdout: true, script: "./gradlew sonarqube -Dsonar.host.url=${SONARQUBE_URL} -Dsonar.projectKey='invasives-app' -Dsonar.verbose=true --stacktrace --info"
+//                         sleep(30)
 
-                        // check if sonarqube passed
-                        sh("oc extract secret/sonarqube-status-urls --to=${env.WORKSPACE}/sonar-runner --confirm")
-                        SONARQUBE_STATUS_JSON = sh(returnStdout: true, script: "curl -w '%{http_code}' '${SONARQUBE_STATUS_URL}'")
-                        SONARQUBE_STATUS = sonarGetStatus (SONARQUBE_STATUS_JSON)
+//                         // check if sonarqube passed
+//                         sh("oc extract secret/sonarqube-status-urls --to=${env.WORKSPACE}/sonar-runner --confirm")
+//                         SONARQUBE_STATUS_JSON = sh(returnStdout: true, script: "curl -w '%{http_code}' '${SONARQUBE_STATUS_URL}'")
+//                         SONARQUBE_STATUS = sonarGetStatus (SONARQUBE_STATUS_JSON)
 
-                        if ( "${SONARQUBE_STATUS}" == "ERROR") {
-                            echo "Sonarqube scan failed"
-                            currentBuild.result = 'FAILURE'
-                            exit 1
-                        } else {
-                            echo "Sonarqube scan passed"
-                        }
-                    } catch (error) {
-                        echo ${error}
-                        throw error
-                    } finally {
-                        echo "Sonarqube scan complete"
-                    }
-                }
-            }
-        }
-        return true
-    }
-}
+//                         if ( "${SONARQUBE_STATUS}" == "ERROR") {
+//                             echo "Sonarqube scan failed"
+//                             currentBuild.result = 'FAILURE'
+//                             exit 1
+//                         } else {
+//                             echo "Sonarqube scan passed"
+//                         }
+//                     } catch (error) {
+//                         echo ${error}
+//                         throw error
+//                     } finally {
+//                         echo "Sonarqube scan complete"
+//                     }
+//                 }
+//             }
+//         }
+//         return true
+//     }
+// }
 
 pipeline {
     agent none
@@ -176,20 +176,20 @@ pipeline {
                 sh "cd api/.pipeline && ./npmw ci && DEBUG=* ./npmw run seed -- --pr=${CHANGE_ID} --env=dev --type=static"
             }
         }
-        stage('Sonarqube') {
-            agent {
-                label 'deploy'
-            }
-            when {
-                environment name : 'CHANGE_TARGET', value: 'dev'
-            }
-            steps {
-                script {
-                    echo "Running Sonarqube"
-                    def result = nodejsSonarqube()
-                }
-            }
-        }
+        // stage('Sonarqube') {
+        //     agent {
+        //         label 'deploy'
+        //     }
+        //     when {
+        //         environment name : 'CHANGE_TARGET', value: 'dev'
+        //     }
+        //     steps {
+        //         script {
+        //             echo "Running Sonarqube"
+        //             def result = nodejsSonarqube()
+        //         }
+        //     }
+        // }
         stage('Deploy (Dev) API/APP [Static]') {
             agent {
                 label 'deploy'
